### ISSUE TITLE
Calculation method changed?

### ISSUE THREAD

**Issue by AlexanderDerck** [Zaczero/CBBI#13]
First of all, thanks for creating this index. I've been following it for a while and check it daily. Yesterday I saw the CBBI score was 9, but when I checked it today it's suddenly at 14? Also all the historic values have changed, so I wonder what was changed in the algorithm and why?

**Comment by Zaczero** [comment]
Something bugged out. Will investigate today.

**Comment by Zaczero** [comment]
Fixed in 167f7c3c2f9305e03220450b78fb6717d5918c28. Waiting for Colin to push the updates to the [cbbi.info](https://cbbi.info). The new score for today is 5.
