### ISSUE TITLE
RHOLD and RR not calibrated. 

### ISSUE THREAD

**Issue by neardaniel-pls** [Zaczero/CBBI#15]
Due to alpha decay these two indicators suffered the most and seem inconsistent. Is it possible a small calibration?

**Comment by Zaczero** [comment]
We do plan to perform general CBBI calibration soon. We are just waiting for a relatively good/low activity time. Possibly <30 days. We will announce it as this will move the scores a little bit and we don't want to leave people wondering. :-)

**Comment by Zaczero** [comment]
Metrics have now been re aligned.
