### ISSUE TITLE
RHODL Ratio broken?

### ISSUE THREAD

**Issue by agambon** [Zaczero/CBBI#17]
The site currently indicates that the RHODL ratio is at 100%. Unless I am misunderstanding how the CBBI normalizes the metrics, this seems incorrect. Perhaps the data scraper is broken or something? 
![image](https://github.com/user-attachments/assets/52788693-c50e-408e-a0c8-d8fdc6429d83)

**Comment by ColinTalksCrypto** [comment]
Hello, this actually isn't a bug. It's at 100 due to the upper regression
line (which is used to account for diminishing returns). This is why we
have 9 metrics and the confidence score is an average among them. If
there's any you don't feel comfortable using, you can choose to deselect it
and get your own custom score. -Colin

**Comment by Zaczero** [comment]
Looking at the chart https://coinank.com/indexdata/rhodlRatio, you can see that the previous peak was quite off the prediction, so CBBI is automatically adjusting for this change. And we are at similar levels as the 2021 peak - thus the 100% score.

**Comment by ColinTalksCrypto** [comment]
I looked into this more closely. As you've drawn it, @Zaczero, is how I agree it should look. However, this upper trend line currently looks more like the **red** line, as pictured here:

![Image](https://github.com/user-attachments/assets/3a71edb8-120e-498f-b1e5-8b113bc4c14d)

I think we should adjust it to be more like the **blue** line as shown in same image. I've opened a new git issue to elaborate on this in more detail. See #18 

- Colin


> Looking at the chart https://coinank.com/indexdata/rhodlRatio, you can see that the previous peak was quite off the prediction, so CBBI is automatically adjusting for this change. And we are at similar levels as the 2021 peak - thus the 100% score.
> 
> Something like that: ![image](https://github.com/user-attachments/assets/4bae9794-cd79-490f-9a3a-e028f047e033)
