### ISSUE TITLE
Response problem!

### ISSUE THREAD

**Issue by ozdemibr** [Zaczero/CBBI#2]
Hi my friend. Thanks for your effort but i've a problem for a few days.

New json url address is: https://www.lookintobitcoin.com/django_plotly_dash/app/unrealised_profit_loss/_dash-update-component

But i can't this url execute directly on browser and i get "Server Error (500)".

However i can execute it with browser developer tools. How can i get it with Python code?

Thanks.

**Comment by Zaczero** [comment]
Hello! lookintobitcoin.com has indeed updated their API system. You can see what has been changed in the code in order to make it work again here: https://github.com/Zaczero/CBBI/commit/0fb451c510a7343b3fbbfe6da26b0103ebbcf10c Thanks for reporting the issue.
