### ISSUE TITLE
Other indicators

### ISSUE THREAD

**Issue by davidpasini** [Zaczero/CBBI#3]
Hi Kamil!

Thank you so much for this amazing project. I was wondering whether you are planning to include all other indicators from lookintobitcoi.com.

Keep up the amazing work! :)

**Comment by Zaczero** [comment]
Hello @davidpasini, we are currently not planning to include all the indicators from the LIB website. Instead, our goal is to stick to just 10-13 community-approved metrics, which may be sourced from various websites. Colin usually handles most of the conversations on that topic on Twitter: https://twitter.com/ColinTCrypto.
