### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by bousalman** [Zaczero/CBBI#6]
Hi there,

the website https://www.lookintobitcoin.com/django_plotly_dash/app/rhodl_ratio/_dash-update-component is not working, having 500 error.
maybe need to have a mirrors or exception handling for these cases.

Regards,

**Comment by bousalman** [comment]
I can see that there was prior issues about this problem.

**Comment by Zaczero** [comment]
Just letting you know that we will be implementing a GlassNode fallback shortly.
